from __future__ import annotations

DEFAULT_WEB_SEARCH_PROVIDER = "parallel"
DEFAULT_WEB_SEARCH_MAX_RESULTS = 5
DEFAULT_WEB_SEARCH_TIMEOUT_SECONDS = 8.0
DEFAULT_WEB_SEARCH_BENCHMARK_OUTPUT = "search-benchmark.json"

WEB_SEARCH_PROVIDER_ENV = "WEB_SEARCH_PROVIDER"
WEB_SEARCH_MAX_RESULTS_ENV = "WEB_SEARCH_MAX_RESULTS"
WEB_SEARCH_TIMEOUT_SECONDS_ENV = "WEB_SEARCH_TIMEOUT_SECONDS"
WEB_SEARCH_BENCHMARK_OUTPUT_ENV = "WEB_SEARCH_BENCHMARK_OUTPUT"

PARALLEL_PROVIDER = "parallel"
EXA_PROVIDER = "exa"
PERPLEXITY_PROVIDER = "perplexity"
SUPPORTED_WEB_SEARCH_PROVIDERS = (
    PARALLEL_PROVIDER,
    EXA_PROVIDER,
    PERPLEXITY_PROVIDER,
)

PROVIDER_SECRET_NAMES = {
    PARALLEL_PROVIDER: "PARALLEL_API_KEY",
    EXA_PROVIDER: "EXA_API_KEY",
    PERPLEXITY_PROVIDER: "PERPLEXITY_API_KEY",
}

ESTIMATED_PROVIDER_COSTS = {
    PARALLEL_PROVIDER: 0.001,
    EXA_PROVIDER: 0.007,
    PERPLEXITY_PROVIDER: 0.005,
}
