export const LIVEKIT_GUEST_SESSION_SECONDS = 2 * 60;
export const LIVEKIT_GUEST_TOKEN_TTL_SECONDS = 45;
export const LIVEKIT_GUEST_ACTIVE_TTL_SECONDS = LIVEKIT_GUEST_SESSION_SECONDS;
export const LIVEKIT_GUEST_CLEANUP_ENABLED =
  process.env.LIVEKIT_GUEST_CLEANUP_ENABLED === "true";
export const LIVEKIT_GUEST_COOLDOWN_ENABLED = false;
export const LIVEKIT_GUEST_COOLDOWN_SECONDS = LIVEKIT_GUEST_SESSION_SECONDS;
export const LIVEKIT_GUEST_SIGNUP_URL = "/api/auth/signin";
export const LIVEKIT_GUEST_ROOM_DEPARTURE_TIMEOUT_SECONDS = 5;

export const LIVEKIT_GUEST_COOKIE_NAME = "lk_guest_device";
export const LIVEKIT_GUEST_REDIS_PREFIX = "livekit:guest";
